# Generated by Django 3.2 on 2021-08-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='price',
            field=models.FloatField(blank=True, default=50000, max_length=100),
            preserve_default=False,
        ),
    ]
