# Generated by Django 3.2 on 2021-08-20 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0004_orderaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderaddress',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='customer',
        ),
    ]
