# Generated by Django 3.2.6 on 2021-10-09 08:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0006_contactinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=500),
        ),
    ]
