# Generated by Django 3.2.6 on 2021-10-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0007_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='testdrive',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
