# Generated by Django 3.2.6 on 2021-12-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0008_auto_20211010_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On-The-Way', 'On The Way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel'), ('pending', 'pending')], default='pending', max_length=50),
        ),
    ]
